
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class NewACCOUNT extends javax.swing.JFrame {

    /**
     * Creates new form NewACCOUNT
     */
    public NewACCOUNT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(470, 200));
        setMinimumSize(new java.awt.Dimension(400, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setDisplayedMnemonic('U');
        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 20)); // NOI18N
        jLabel2.setLabelFor(jTextField1);
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(72, 87, 90, 24);

        jLabel3.setDisplayedMnemonic('P');
        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 20)); // NOI18N
        jLabel3.setLabelFor(jPasswordField1);
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(72, 137, 90, 24);

        jTextField1.setFont(new java.awt.Font("Monotype Corsiva", 1, 20)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(190, 84, 100, 30);

        jPasswordField1.setFont(new java.awt.Font("Monotype Corsiva", 1, 20)); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(190, 134, 100, 30);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 20)); // NOI18N
        jLabel4.setText("Add ACCOUNT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(125, 19, 140, 24);

        jLabel5.setDisplayedMnemonic('S');
        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 20)); // NOI18N
        jLabel5.setLabelFor(jPasswordField2);
        jLabel5.setText("School PIN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(72, 189, 100, 24);

        jPasswordField2.setFont(new java.awt.Font("Monotype Corsiva", 1, 20)); // NOI18N
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(190, 186, 100, 30);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Monotype Corsiva", 1, 20)); // NOI18N
        jButton2.setMnemonic('A');
        jButton2.setText("Add ACCOUNT");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(72, 234, 160, 33);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Monotype Corsiva", 1, 20)); // NOI18N
        jButton3.setMnemonic('R');
        jButton3.setText("Return");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 234, 87, 33);

        jLabel6.setBackground(new java.awt.Color(153, 255, 153));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-10, -10, 430, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String username=jTextField1.getText();
String password=new String(jPasswordField1.getPassword());
String pin=new String(jPasswordField2.getPassword());

if(pin.equals("8520"))
{    int responce=JOptionPane.showConfirmDialog(this,"Confirm Add New Account");
     if(responce==0)
{    try {Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","manager");
        Statement stmt=con.createStatement();
        String AddACCOUNT="insert into accounts values('"+username+"','"+password+"')";
        int check=stmt.executeUpdate(AddACCOUNT);
        con.close();
        JOptionPane.showMessageDialog(this,check+" Account Added Sucessfully");
        } catch (Exception e) {JOptionPane.showMessageDialog(this,e.getMessage());
        }
}
new Login().setVisible(true);
this.dispose();
}
else
{JOptionPane.showMessageDialog(this,"Wrong PIN Entered.");
new Login().setVisible(true);
this.dispose();}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewACCOUNT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
